project_id = "hfkubpcdbjxhafulxhfv"

[api]
port = 54321

[db]
port = 54322
major_version = 15

[auth]
enable_signup = true

[studio]
port = 54323

[functions.hello-world]
import_map = "./import_map.json"

[functions.health-check]
import_map = "./import_map.json"

[functions.rate-limit-check]
import_map = "./import_map.json"

[functions.process-background-jobs]
import_map = "./import_map.json"

[functions.realtime-chat]
import_map = "./import_map.json"

[functions.user-profiles]
import_map = "./import_map.json"

[functions.webrtc-signaling]
import_map = "./import_map.json"

[functions.discussion-room-create]
import_map = "./import_map.json"

[functions.discussion-room-get-messages]
import_map = "./import_map.json"

[functions.discussion-room-join-room]
import_map = "./import_map.json"

[functions.discussion-room-leave-room]
import_map = "./import_map.json"

[functions.discussion-room-list-rooms]
import_map = "./import_map.json"

[functions.discussion-room-update-room]
import_map = "./import_map.json"

[functions.send-notification]
import_map = "./import_map.json"
